import Anthropic from "@anthropic-ai/sdk";
import { NextRequest } from "next/server";
import { buildIngestSystem } from "@/lib/tutor-prompt";

export const runtime = "nodejs";
export const maxDuration = 300;

const MODEL = process.env.TUTOR_MODEL || "claude-sonnet-5";
const MAX_PDF_BYTES = 20 * 1024 * 1024; // 20 MB

/** Accepts a PDF (multipart/form-data, field "file"), returns a structured
 *  chapter JSON generated by Claude for the client-side knowledge base. */
export async function POST(req: NextRequest) {
  if (!process.env.ANTHROPIC_API_KEY) {
    return Response.json(
      {
        error:
          "PDF ingestion needs an ANTHROPIC_API_KEY. Add it to your environment (see README). The seven built-in chapters work without it.",
      },
      { status: 503 }
    );
  }

  let file: File | null = null;
  try {
    const form = await req.formData();
    const f = form.get("file");
    if (f instanceof File) file = f;
  } catch {
    return Response.json(
      { error: "Send the PDF as multipart/form-data with field 'file'." },
      { status: 400 }
    );
  }

  if (!file) {
    return Response.json({ error: "No file received." }, { status: 400 });
  }
  if (file.type !== "application/pdf") {
    return Response.json({ error: "Only PDF files are supported." }, { status: 415 });
  }
  if (file.size > MAX_PDF_BYTES) {
    return Response.json(
      { error: "PDF is larger than 20 MB — split it and upload chapters separately." },
      { status: 413 }
    );
  }

  const bytes = Buffer.from(await file.arrayBuffer()).toString("base64");
  const client = new Anthropic();

  try {
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: 16000,
      system: buildIngestSystem(),
      messages: [
        {
          role: "user",
          content: [
            {
              type: "document",
              source: {
                type: "base64",
                media_type: "application/pdf",
                data: bytes,
              },
            },
            {
              type: "text",
              text: "Convert these lecture notes into the structured chapter JSON. Return only the JSON object.",
            },
          ],
        },
      ],
    });

    const text = response.content
      .filter((b) => b.type === "text")
      .map((b) => (b.type === "text" ? b.text : ""))
      .join("");

    // tolerate accidental code fences
    const jsonText = text.replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/, "");
    let parsed: unknown;
    try {
      parsed = JSON.parse(jsonText);
    } catch {
      return Response.json(
        { error: "The model returned malformed JSON — please try again." },
        { status: 502 }
      );
    }

    if (
      typeof parsed === "object" &&
      parsed !== null &&
      "error" in (parsed as Record<string, unknown>)
    ) {
      return Response.json(
        { error: "That PDF doesn't look like academic notes — nothing was extracted." },
        { status: 422 }
      );
    }

    return Response.json({ chapter: parsed });
  } catch (err) {
    const message =
      err instanceof Anthropic.APIError
        ? `Anthropic API error (${err.status}): ${err.message}`
        : "Unexpected error while processing the PDF.";
    return Response.json({ error: message }, { status: 502 });
  }
}
